tgchannel:
  - https://t.me/dingyue_Center
  - https://t.me/freekankan
  - https://t.me/go4sharing
  - https://t.me/wbnet
  - https://t.me/wxdy666
  - https://t.me/ShareCentrePro
  - https://t.me/TG_2345
  - https://t.me/dns68
  - https://t.me/wz2023jd
  - https://t.me/s/pgkj666
  - https://t.me/SubscriptionShare
  - https://t.me/ccbaohe
  - https://t.me/juzibaipiao
  - https://t.me/freeVPNjd
  - https://t.me/ssrsub
  - https://t.me/v2rayshahin
  - https://t.me/v2queen
  - https://t.me/TGVPN777
  - https://t.me/ZDYZ2
  - https://t.me/ShareCentre
  - https://t.me/changfengchannel
  - https://t.me/hkaa0

websites:
  - https://www.mibei77.com
  - https://clashgithub.com
